version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - data-hub-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - data-hub-network
  # ingestors-financial-mercadobitcoin-tickers:
  #   build:
  #     context: apps/ingestors/financial/mercadobitcoin/tickers
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   networks:
  #     - data-hub-network
networks:
  data-hub-network:
    external: true
    driver: bridge
