name: Monorepo CI

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  workflow-start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The test it has started"

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: source ./.venv/bin/activate
      - run: npx nx test

#       # - run: |
#       #     source ./.venv/bin/activate
#       #     npx nx affected --target=test --parallel=3
