name: Monorepo CI

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Download build artifacts
      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      # Use build artifacts
      - run: source artifacts/activate
      - run: npx nx testgit s
